# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/etf/Desktop/PROJEKAT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/etf/Desktop/PROJEKAT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etf/Desktop/PROJEKAT/CMakeFiles /home/etf/Desktop/PROJEKAT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etf/Desktop/PROJEKAT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/assembler

# Build rule for target.
bin/assembler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/assembler
.PHONY : bin/assembler

# fast build rule for target.
bin/assembler/fast:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/build
.PHONY : bin/assembler/fast

#=============================================================================
# Target rules for targets named bin/emulator

# Build rule for target.
bin/emulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/emulator
.PHONY : bin/emulator

# fast build rule for target.
bin/emulator/fast:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/build
.PHONY : bin/emulator/fast

src/assembler/src/Assembler.o: src/assembler/src/Assembler.cpp.o
.PHONY : src/assembler/src/Assembler.o

# target to build an object file
src/assembler/src/Assembler.cpp.o:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/assembler/src/Assembler.cpp.o
.PHONY : src/assembler/src/Assembler.cpp.o

src/assembler/src/Assembler.i: src/assembler/src/Assembler.cpp.i
.PHONY : src/assembler/src/Assembler.i

# target to preprocess a source file
src/assembler/src/Assembler.cpp.i:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/assembler/src/Assembler.cpp.i
.PHONY : src/assembler/src/Assembler.cpp.i

src/assembler/src/Assembler.s: src/assembler/src/Assembler.cpp.s
.PHONY : src/assembler/src/Assembler.s

# target to generate assembly for a file
src/assembler/src/Assembler.cpp.s:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/assembler/src/Assembler.cpp.s
.PHONY : src/assembler/src/Assembler.cpp.s

src/assembler/src/main.o: src/assembler/src/main.cpp.o
.PHONY : src/assembler/src/main.o

# target to build an object file
src/assembler/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/assembler/src/main.cpp.o
.PHONY : src/assembler/src/main.cpp.o

src/assembler/src/main.i: src/assembler/src/main.cpp.i
.PHONY : src/assembler/src/main.i

# target to preprocess a source file
src/assembler/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/assembler/src/main.cpp.i
.PHONY : src/assembler/src/main.cpp.i

src/assembler/src/main.s: src/assembler/src/main.cpp.s
.PHONY : src/assembler/src/main.s

# target to generate assembly for a file
src/assembler/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/assembler/src/main.cpp.s
.PHONY : src/assembler/src/main.cpp.s

src/emulator/src/Emulator.o: src/emulator/src/Emulator.cpp.o
.PHONY : src/emulator/src/Emulator.o

# target to build an object file
src/emulator/src/Emulator.cpp.o:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/Emulator.cpp.o
.PHONY : src/emulator/src/Emulator.cpp.o

src/emulator/src/Emulator.i: src/emulator/src/Emulator.cpp.i
.PHONY : src/emulator/src/Emulator.i

# target to preprocess a source file
src/emulator/src/Emulator.cpp.i:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/Emulator.cpp.i
.PHONY : src/emulator/src/Emulator.cpp.i

src/emulator/src/Emulator.s: src/emulator/src/Emulator.cpp.s
.PHONY : src/emulator/src/Emulator.s

# target to generate assembly for a file
src/emulator/src/Emulator.cpp.s:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/Emulator.cpp.s
.PHONY : src/emulator/src/Emulator.cpp.s

src/emulator/src/Linker.o: src/emulator/src/Linker.cpp.o
.PHONY : src/emulator/src/Linker.o

# target to build an object file
src/emulator/src/Linker.cpp.o:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/Linker.cpp.o
.PHONY : src/emulator/src/Linker.cpp.o

src/emulator/src/Linker.i: src/emulator/src/Linker.cpp.i
.PHONY : src/emulator/src/Linker.i

# target to preprocess a source file
src/emulator/src/Linker.cpp.i:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/Linker.cpp.i
.PHONY : src/emulator/src/Linker.cpp.i

src/emulator/src/Linker.s: src/emulator/src/Linker.cpp.s
.PHONY : src/emulator/src/Linker.s

# target to generate assembly for a file
src/emulator/src/Linker.cpp.s:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/Linker.cpp.s
.PHONY : src/emulator/src/Linker.cpp.s

src/emulator/src/MemAllocator.o: src/emulator/src/MemAllocator.cpp.o
.PHONY : src/emulator/src/MemAllocator.o

# target to build an object file
src/emulator/src/MemAllocator.cpp.o:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/MemAllocator.cpp.o
.PHONY : src/emulator/src/MemAllocator.cpp.o

src/emulator/src/MemAllocator.i: src/emulator/src/MemAllocator.cpp.i
.PHONY : src/emulator/src/MemAllocator.i

# target to preprocess a source file
src/emulator/src/MemAllocator.cpp.i:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/MemAllocator.cpp.i
.PHONY : src/emulator/src/MemAllocator.cpp.i

src/emulator/src/MemAllocator.s: src/emulator/src/MemAllocator.cpp.s
.PHONY : src/emulator/src/MemAllocator.s

# target to generate assembly for a file
src/emulator/src/MemAllocator.cpp.s:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/MemAllocator.cpp.s
.PHONY : src/emulator/src/MemAllocator.cpp.s

src/emulator/src/ObjectFile.o: src/emulator/src/ObjectFile.cpp.o
.PHONY : src/emulator/src/ObjectFile.o

# target to build an object file
src/emulator/src/ObjectFile.cpp.o:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/ObjectFile.cpp.o
.PHONY : src/emulator/src/ObjectFile.cpp.o

src/emulator/src/ObjectFile.i: src/emulator/src/ObjectFile.cpp.i
.PHONY : src/emulator/src/ObjectFile.i

# target to preprocess a source file
src/emulator/src/ObjectFile.cpp.i:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/ObjectFile.cpp.i
.PHONY : src/emulator/src/ObjectFile.cpp.i

src/emulator/src/ObjectFile.s: src/emulator/src/ObjectFile.cpp.s
.PHONY : src/emulator/src/ObjectFile.s

# target to generate assembly for a file
src/emulator/src/ObjectFile.cpp.s:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/ObjectFile.cpp.s
.PHONY : src/emulator/src/ObjectFile.cpp.s

src/emulator/src/main.o: src/emulator/src/main.cpp.o
.PHONY : src/emulator/src/main.o

# target to build an object file
src/emulator/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/main.cpp.o
.PHONY : src/emulator/src/main.cpp.o

src/emulator/src/main.i: src/emulator/src/main.cpp.i
.PHONY : src/emulator/src/main.i

# target to preprocess a source file
src/emulator/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/main.cpp.i
.PHONY : src/emulator/src/main.cpp.i

src/emulator/src/main.s: src/emulator/src/main.cpp.s
.PHONY : src/emulator/src/main.s

# target to generate assembly for a file
src/emulator/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/emulator/src/main.cpp.s
.PHONY : src/emulator/src/main.cpp.s

src/helpers/src/Directive.o: src/helpers/src/Directive.cpp.o
.PHONY : src/helpers/src/Directive.o

# target to build an object file
src/helpers/src/Directive.cpp.o:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Directive.cpp.o
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Directive.cpp.o
.PHONY : src/helpers/src/Directive.cpp.o

src/helpers/src/Directive.i: src/helpers/src/Directive.cpp.i
.PHONY : src/helpers/src/Directive.i

# target to preprocess a source file
src/helpers/src/Directive.cpp.i:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Directive.cpp.i
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Directive.cpp.i
.PHONY : src/helpers/src/Directive.cpp.i

src/helpers/src/Directive.s: src/helpers/src/Directive.cpp.s
.PHONY : src/helpers/src/Directive.s

# target to generate assembly for a file
src/helpers/src/Directive.cpp.s:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Directive.cpp.s
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Directive.cpp.s
.PHONY : src/helpers/src/Directive.cpp.s

src/helpers/src/ExprRelocation.o: src/helpers/src/ExprRelocation.cpp.o
.PHONY : src/helpers/src/ExprRelocation.o

# target to build an object file
src/helpers/src/ExprRelocation.cpp.o:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/ExprRelocation.cpp.o
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/ExprRelocation.cpp.o
.PHONY : src/helpers/src/ExprRelocation.cpp.o

src/helpers/src/ExprRelocation.i: src/helpers/src/ExprRelocation.cpp.i
.PHONY : src/helpers/src/ExprRelocation.i

# target to preprocess a source file
src/helpers/src/ExprRelocation.cpp.i:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/ExprRelocation.cpp.i
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/ExprRelocation.cpp.i
.PHONY : src/helpers/src/ExprRelocation.cpp.i

src/helpers/src/ExprRelocation.s: src/helpers/src/ExprRelocation.cpp.s
.PHONY : src/helpers/src/ExprRelocation.s

# target to generate assembly for a file
src/helpers/src/ExprRelocation.cpp.s:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/ExprRelocation.cpp.s
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/ExprRelocation.cpp.s
.PHONY : src/helpers/src/ExprRelocation.cpp.s

src/helpers/src/Expression.o: src/helpers/src/Expression.cpp.o
.PHONY : src/helpers/src/Expression.o

# target to build an object file
src/helpers/src/Expression.cpp.o:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Expression.cpp.o
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Expression.cpp.o
.PHONY : src/helpers/src/Expression.cpp.o

src/helpers/src/Expression.i: src/helpers/src/Expression.cpp.i
.PHONY : src/helpers/src/Expression.i

# target to preprocess a source file
src/helpers/src/Expression.cpp.i:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Expression.cpp.i
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Expression.cpp.i
.PHONY : src/helpers/src/Expression.cpp.i

src/helpers/src/Expression.s: src/helpers/src/Expression.cpp.s
.PHONY : src/helpers/src/Expression.s

# target to generate assembly for a file
src/helpers/src/Expression.cpp.s:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Expression.cpp.s
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Expression.cpp.s
.PHONY : src/helpers/src/Expression.cpp.s

src/helpers/src/Instruction.o: src/helpers/src/Instruction.cpp.o
.PHONY : src/helpers/src/Instruction.o

# target to build an object file
src/helpers/src/Instruction.cpp.o:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Instruction.cpp.o
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Instruction.cpp.o
.PHONY : src/helpers/src/Instruction.cpp.o

src/helpers/src/Instruction.i: src/helpers/src/Instruction.cpp.i
.PHONY : src/helpers/src/Instruction.i

# target to preprocess a source file
src/helpers/src/Instruction.cpp.i:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Instruction.cpp.i
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Instruction.cpp.i
.PHONY : src/helpers/src/Instruction.cpp.i

src/helpers/src/Instruction.s: src/helpers/src/Instruction.cpp.s
.PHONY : src/helpers/src/Instruction.s

# target to generate assembly for a file
src/helpers/src/Instruction.cpp.s:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Instruction.cpp.s
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Instruction.cpp.s
.PHONY : src/helpers/src/Instruction.cpp.s

src/helpers/src/Section.o: src/helpers/src/Section.cpp.o
.PHONY : src/helpers/src/Section.o

# target to build an object file
src/helpers/src/Section.cpp.o:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Section.cpp.o
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Section.cpp.o
.PHONY : src/helpers/src/Section.cpp.o

src/helpers/src/Section.i: src/helpers/src/Section.cpp.i
.PHONY : src/helpers/src/Section.i

# target to preprocess a source file
src/helpers/src/Section.cpp.i:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Section.cpp.i
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Section.cpp.i
.PHONY : src/helpers/src/Section.cpp.i

src/helpers/src/Section.s: src/helpers/src/Section.cpp.s
.PHONY : src/helpers/src/Section.s

# target to generate assembly for a file
src/helpers/src/Section.cpp.s:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Section.cpp.s
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Section.cpp.s
.PHONY : src/helpers/src/Section.cpp.s

src/helpers/src/Symbol.o: src/helpers/src/Symbol.cpp.o
.PHONY : src/helpers/src/Symbol.o

# target to build an object file
src/helpers/src/Symbol.cpp.o:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Symbol.cpp.o
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Symbol.cpp.o
.PHONY : src/helpers/src/Symbol.cpp.o

src/helpers/src/Symbol.i: src/helpers/src/Symbol.cpp.i
.PHONY : src/helpers/src/Symbol.i

# target to preprocess a source file
src/helpers/src/Symbol.cpp.i:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Symbol.cpp.i
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Symbol.cpp.i
.PHONY : src/helpers/src/Symbol.cpp.i

src/helpers/src/Symbol.s: src/helpers/src/Symbol.cpp.s
.PHONY : src/helpers/src/Symbol.s

# target to generate assembly for a file
src/helpers/src/Symbol.cpp.s:
	$(MAKE) -f CMakeFiles/bin/assembler.dir/build.make CMakeFiles/bin/assembler.dir/src/helpers/src/Symbol.cpp.s
	$(MAKE) -f CMakeFiles/bin/emulator.dir/build.make CMakeFiles/bin/emulator.dir/src/helpers/src/Symbol.cpp.s
.PHONY : src/helpers/src/Symbol.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bin/assembler"
	@echo "... bin/emulator"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/assembler/src/Assembler.o"
	@echo "... src/assembler/src/Assembler.i"
	@echo "... src/assembler/src/Assembler.s"
	@echo "... src/assembler/src/main.o"
	@echo "... src/assembler/src/main.i"
	@echo "... src/assembler/src/main.s"
	@echo "... src/emulator/src/Emulator.o"
	@echo "... src/emulator/src/Emulator.i"
	@echo "... src/emulator/src/Emulator.s"
	@echo "... src/emulator/src/Linker.o"
	@echo "... src/emulator/src/Linker.i"
	@echo "... src/emulator/src/Linker.s"
	@echo "... src/emulator/src/MemAllocator.o"
	@echo "... src/emulator/src/MemAllocator.i"
	@echo "... src/emulator/src/MemAllocator.s"
	@echo "... src/emulator/src/ObjectFile.o"
	@echo "... src/emulator/src/ObjectFile.i"
	@echo "... src/emulator/src/ObjectFile.s"
	@echo "... src/emulator/src/main.o"
	@echo "... src/emulator/src/main.i"
	@echo "... src/emulator/src/main.s"
	@echo "... src/helpers/src/Directive.o"
	@echo "... src/helpers/src/Directive.i"
	@echo "... src/helpers/src/Directive.s"
	@echo "... src/helpers/src/ExprRelocation.o"
	@echo "... src/helpers/src/ExprRelocation.i"
	@echo "... src/helpers/src/ExprRelocation.s"
	@echo "... src/helpers/src/Expression.o"
	@echo "... src/helpers/src/Expression.i"
	@echo "... src/helpers/src/Expression.s"
	@echo "... src/helpers/src/Instruction.o"
	@echo "... src/helpers/src/Instruction.i"
	@echo "... src/helpers/src/Instruction.s"
	@echo "... src/helpers/src/Section.o"
	@echo "... src/helpers/src/Section.i"
	@echo "... src/helpers/src/Section.s"
	@echo "... src/helpers/src/Symbol.o"
	@echo "... src/helpers/src/Symbol.i"
	@echo "... src/helpers/src/Symbol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

